#!/usr/bin/env bash

set -eu

# Install requirements
pip install -r /lambda/requirements.txt
rm /lambda/requirements.txt

# Create zip
cd /lambda/
zip -9 /deploy/function.zip *
cd /usr/local/lib64/python2.7/site-packages
zip -r9 /deploy/function.zip *
cd /usr/local/lib/python2.7/site-packages
zip -r9 /deploy/function.zip *

if [ -z ${AWS_PROFILE+1} ]; then
    aws lambda update-function-code --profile ${AWS_PROFILE} --function-name ${LAMBDA_FUNCTION_NAME} --zip-file fileb:///deploy/function.zip
else
    aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --zip-file fileb:///deploy/function.zip
fi